eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-helloworld
  datasource:
    grdm:
      url: jdbc:oracle:thin:@10.16.66.234:1602:gplmtst2
      username: rdm
      password: rdm_test
      driver-class-name: oracle.jdbc.driver.OracleDriver
      minIdle: 2
      initialSize: 2
      maxActive: 50